* Learn Go With Tests
Following along with https://quii.gitbook.io/learn-go-with-tests/

* Hello, World
- Had to turn on yasnippet minor mode to have golang completions work
- I have my editor configured to display tabs as two spaces to make golang more accessible for me
- I have opted to edit files directly rather than tangling so that I can get the benefit of LSP integration in golang
  - [ ] There may be a good way to make it work inside Org-mode but I haven't investigated
  - Pretty cool to be able to test compiler errors in the editor without needing to run the tests :sunglasses:

** Go modules
- [ ] Can I get =go test= to report using dots?

To see a module's godocs:

#+begin_src sh
  godoc -http :8000
#+end_src

** Can I watch and rerun tests?
- Not through =go test= directly :(
- I can do some shenanigans with =fswatch= (an OS X tool, similar tools exist for other operating systems)
- Install with =brew install fswatch=

#+begin_src sh
  fswatch -o ./*.go | xargs -n1 -I{} go test
#+end_src

See https://emcrisostomo.github.io/fswatch/usage.html

** Hello, world... again
This is interesting:

#+begin_quote
=t.Helper()= is needed to tell the test suite that this method is a helper. By doing this when it fails the line number reported will be in our function call rather than inside our test helper. This will help other developers track down problems easier.
#+end_quote

This is a feature of Playwright that I prefer as well.

Doesn't look like Go has syntactic sugar for default values for function parameters :( https://stackoverflow.com/questions/19612449/default-value-in-gos-method#comment77755758_23650312
